### ISSUE TITLE
Trigger onChange when date is not valid

### ISSUE THREAD

**Issue by agustingazzano** [wojtekmaj/react-datetime-picker#153]
At the moment there is no way of knowing if the current date is valid or not. If I want to use this component in a submittable form I need to know the date that is currently on the field and not the last valid date, which is what it does by default.

**Comment by cjmaria** [comment]
That PR (which has been merged) seems to do something slightly different than what op is describing. While it prevents invalid datetimes from being reflected in onChange, it still allows room for the last selected datetime to be not what the user intended.

For instance, if I am entering a time of 8:98 PM, onChange will first call back with 8:09 because it parses the "9" in "98" as a single-digit time. When I proceed to hit 8, it will not trigger an onChange callback because 98 is an invalid minute value. However, if you are saving the time state using onChange, you will have inaccurately stored 8:09 and have no way of telling that this was part of an invalid time. This would require a separate onInvalid callback.
