### ISSUE TITLE
Unable to select date when rendered using portal

### ISSUE THREAD

**Issue by tabrez96** [wojtekmaj/react-datetime-picker#191]
When calendar is rendered using portal, selecting a date from calendar is not triggering onChange. 

Demo: https://codesandbox.io/s/dreamy-pasteur-zm96pl?file=/src/App.js

**Comment by VanixIsHere** [comment]
Bumping this because I am also experiencing this issue when using portalContainer. I've been troubleshooting for quite a while and I can't seem to get any event from the calendar to trigger. This includes onClickDay, onClickMonth, etc. I'm guessing there is a problem with the way the calendar events are bubbling?

It also may be that the 'clickaway' functionality is getting in the way of the portal. For example, if you don't use a portal and right click inside the calendar, the calendar stays open. However if you right click inside the calendar while it's rendered in the portalContainer, it will close immediately.

Maybe there is a workaround that I'm not aware of?

Revised Demo from first post: https://codesandbox.io/s/async-wood-mqe1m0?from-embed=&file=/src/App.js

**Comment by wojtekmaj** [comment]
Looks like `onOutsideAction` fails to recognize that, in fact, we're not clicking outside the calendar.

**Comment by wojtekmaj** [comment]
Fixed in v4.1.1.
