### ISSUE TITLE
Styling looks off

### ISSUE THREAD

**Issue by shahar4** [wojtekmaj/react-datetime-picker#29]
Hey wojtekmaj,

Great work on the picker! It is great -- thanks!

Would you be able to share the configuration that let to the picker to look like it does in your demo?

If not, would you be able to let me know how to get rid of these underlines?
![screen shot 2018-08-19 at 2 54 54 pm](https://user-images.githubusercontent.com/17016473/44308514-fb992980-a3bf-11e8-91cc-c95b33c675a6.png)

Thanks!

**Comment by wojtekmaj** [comment]
It looks like some additional styles are applied to `<input>` elements which React-DateTime-Picker is not resetting. You should use Developer tools to figure out which are the ones and overwrite them.

I could also, once I know which CSS is applied, add CSS resetting it to my default styles so that won't happen for other folks out there.
