### ISSUE TITLE
Calender doesn't automatically close when entering a time

### ISSUE THREAD

**Issue by Rixtho** [wojtekmaj/react-datetime-picker#355]
I use the date-time picker without the clock pop-up. When I click the year/month/day input field to start entering a date the calendar pop-up also opens which is expected behaviour. But when I enter the time at the end the pop-up should close again. It doesn't provide any value when I enter the time and it might even cover up other elements.

**Comment by Rixtho** [comment]
Another thing I noticed is that when I start entering the time first and then go to the other input fields with `tab` the calender pop-up doesn't open at all. I have to click somewhere else on the screen and then select the year/month/day input field again for the calendar to show.

**Comment by vlad2689** [comment]
> Another thing I noticed is that when I start entering the time first and then go to the other input fields with `tab` the calender pop-up doesn't open at all. I have to click somewhere else on the screen and then select the year/month/day input field again for the calendar to show.

Hi @Rixtho, I have the same issue. After some investigation, I found that the issue comes from the following check: https://github.com/wojtekmaj/react-datetime-picker/commit/b753ffa62522ec4c225e598eb5626392b8ae2104#diff-736e0c388d54290d557a9c5ce11afc2623157a4641476336c30bb276944f60e5R189; namely, when the calendar is already opened, it won't open the clock. 

This behaviour seems to have been introduced ~2 months ago. Since this is working properly on the demo, my assumption is that this version of this code hasn't been deployed on the demo.

My assumption is, that by adding these extra checks for `isCalendarOpen` and `isClockOpen`, the author meant to not "re-open" something that was already open.

**Comment by vlad2689** [comment]
I've created a PR for the behaviour of the calendar and clock not switching between each other as a user focuses different inputs.

**Comment by wojtekmaj** [comment]
Fixed in #381.
