### ISSUE TITLE
Display only date without time 

### ISSUE THREAD

**Issue by lavarajallu** [wojtekmaj/react-datetime-picker#37]
I need to only display the date without time.
present date displayed like "10/20/2018 12:00 AM"  but i need to display date like "10/20/2018".Please help me out of this issue

**Comment by marcoancona** [comment]
I would also like to see a boolean prop to enable/disable the time component. There many scenarios where the user can switch between selecting a date-time and selecting a date, ie. a calendar application with all-day or timed events. I would like to handle the two cases with a single component instead of installing two dependencies and loading them alternatively.

**Comment by wojtekmaj** [comment]
Again, use [React-Date-Picker](/wojtekmaj/react-date-picker) :) It belongs to the same family of projects, and because of that using these two at the same time **will not make your bundle heavier**.

**Comment by omkarj739** [comment]
react-date-picker also takes date  and time as output

**Comment by NarendraSai-Infolob** [comment]
Otherwise we can also use slice()
