### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by eric248550** [wojtekmaj/react-datetime-picker#380]
I have been experiencing this problem with NextJS (all good with reactjs) 

In my opinion, it's because NextJS is not comfortable having a other (p tag) wrapping divs or sections

or this library relying on something that could differ between pre-rendering and the browser. (window API)

**Comment by wojtekmaj** [comment]
Try passing custom `format` and/or `locale`. Oftentimes, detection of these is different on the server and the client.

**Comment by douglasrcjames** [comment]
I am also having this issue with Next.js v13.4.9, seems to still be functional but awfully annoying error message. I attempted to set `locale`,  `format`, and `suppressHydrationWarning={true}` as well, but error persists. Have you gotten this library working in a Next.js 13+ project without this error message? This is a pretty common error with Next.js 13 so it may be one of those things just fixed with time as Next.js matures.
