### ISSUE TITLE
How to disable "TimePicker" ?

### ISSUE THREAD

**Issue by ningappa** [wojtekmaj/react-datetime-picker#65]
Hi.
Not sure whether this is new requirement or this feature is  already exist.

I want to have state like disableTimePicker as props to the diasable TimeSelector alone.

How do I do that?

Thanks

**Comment by wojtekmaj** [comment]
`disabled` prop?

**Comment by ningappa** [comment]
```disabled```  intended to whole component.

My requirement is, when i  make ```disableTimePicker=true``` i should be allowed to select only date, not the time. Time selector should be disabled.

**Comment by wojtekmaj** [comment]
Ah, I see. Hmmm, since there is no need for editing hours, they don't need to be inside inputs at all, I think. You could have your `format` prop set to e.g.:

```jsx
format={`dd/MM/yyyy 12:34`}
```

The only thing is you would need to add the time yourself to `onChange` result.
Have a look at a full sample implementation:

https://codesandbox.io/s/react-datetime-picker-with-only-date-editable-99xpr

**Comment by ningappa** [comment]
Alright. 
Thank you. It was much needed.  You suggestion works good. though it was not looking like *disabled* . 

well...
You could consider to have a disableTimePicker props for UI look and feel.

**Comment by wojtekmaj** [comment]
You could play with the styling a little, like apply grey to all elements, but black to inputs.
