### ISSUE TITLE
Getting error, cannot compile

### ISSUE THREAD

**Issue by FilipMasar** [wojtekmaj/react-datetime-picker#92]
Hi, I am getting this error messege. Could you please help me figure out, what is going on.

```
/Users/filip/Documents/shopify/Apps/Timer/node_modules/react-calendar/dist/Calendar.css:1
┃ .react-calendar {
┃ ^
┃ 
┃ SyntaxError: Unexpected token .
┃     at Module._compile (internal/modules/cjs/loader.js:718:23)
┃     at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
┃     at Object.newLoader [as .js] (/Users/filip/Documents/shopify/Apps/Timer/node_modules/pirates/lib/index.js:104:7)
┃     at Module.load (internal/modules/cjs/loader.js:641:32)
┃     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
┃     at Module.require (internal/modules/cjs/loader.js:681:19)
┃     at require (internal/modules/cjs/helpers.js:16:16)
┃     at Object.<anonymous> (/Users/filip/Documents/shopify/Apps/Timer/node_modules/react-datetime-picker/dist/entry.js:8:1)
┃     at Module._compile (internal/modules/cjs/loader.js:774:30)
┃     at Module._compile (/Users/filip/Documents/shopify/Apps/Timer/node_modules/pirates/lib/index.js:99:24)
┃     at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
┃     at Object.newLoader [as .js] (/Users/filip/Documents/shopify/Apps/Timer/node_modules/pirates/lib/index.js:104:7)
┃     at Module.load (internal/modules/cjs/loader.js:641:32)
┃     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
┃     at Module.require (internal/modules/cjs/loader.js:681:19)
┃     at require (internal/modules/cjs/helpers.js:16:16)
┃ [ event ] disposing inactive page(s): /settings, /next/dist/pages/_error
```

**Comment by Closery** [comment]
Yes, I have same error with Next JS and I think the problem is my webpack config but I'm not sure what can I do.

My log:
`SyntaxError: Unexpected token '.'
(anonymous function)
/home/closery/Projects/myApp/node_modules/react-calendar/dist/Calendar.css:1
Module._compile
internal/modules/cjs/loader.js:895:18
Module._extensions..js
internal/modules/cjs/loader.js:995:10
Module.load
internal/modules/cjs/loader.js:815:32
Function.Module._load
internal/modules/cjs/loader.js:727:14
Module.require
internal/modules/cjs/loader.js:852:19
require
internal/modules/cjs/helpers.js:74:18
(anonymous function)
/home/closery/Projects/myApp/node_modules/react-datetime-picker/dist/entry.js:8:1
Module._compile
internal/modules/cjs/loader.js:959:30
Module._extensions..js
internal/modules/cjs/loader.js:995:10
Module.load
internal/modules/cjs/loader.js:815:32
Function.Module._load
internal/modules/cjs/loader.js:727:14
Module.require
internal/modules/cjs/loader.js:852:19
require
internal/modules/cjs/helpers.js:74:18
react-datetime-picker
webpack:/external "react-datetime-picker":1
> 1 | module.exports = require("react-datetime-picker");
View compiled
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../components/ilan-detay/TeklifVer.js
/_next/development/server/static/development/pages/ilan-detay.js:1116:79
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.`

My config file:
`// next.config.js
const withCSS = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
const withImages = require('next-images');

module.exports = withCSS( withSass( withImages({
    module: {
        rules: [
            {
                test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/i,
                use: [
                    {
                        loader: 'file-loader',
                    },
                ],
            },
        ],
    },
})));`

**Comment by wojtekmaj** [comment]
See https://github.com/wojtekmaj/react-date-picker/issues/68
